import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import type {SidebarItemConfig} from '@docusaurus/plugin-content-docs/src/sidebars/types';
import * as fs from 'fs';
import * as path from 'path';

// Helper: only include the category if the directory exists and has content
function categoryIfExists(
  label: string,
  dirName: string,
): SidebarItemConfig[] {
  const dirPath = path.join(__dirname, 'docs', dirName);
  if (fs.existsSync(dirPath)) {
    return [
      {
        type: 'category',
        label,
        items: [{type: 'autogenerated', dirName}],
      },
    ];
  }
  return [];
}

const sidebars: SidebarsConfig = {
  apisSidebar: [
    'intro',
    ...categoryIfExists('APIs e Fontes de Dados', 'apis'),
    ...categoryIfExists('Receitas de Cruzamento', 'cruzamentos'),
    'como-contribuir',
  ],
};

export default sidebars;
